name: 'Run Smithers Agent'
description: 'Execute a Smithers AI agent in your CI/CD pipeline'
author: 'Smithers AI'
branding:
  icon: 'cpu'
  color: 'blue'

inputs:
  agent:
    description: 'Path to agent file (.mdx or .tsx)'
    required: true

  config:
    description: 'Path to smithers config file'
    required: false

  mock:
    description: 'Run in mock mode (no API calls)'
    required: false
    default: 'false'

  anthropic-api-key:
    description: 'Anthropic API key'
    required: false

  max-frames:
    description: 'Maximum execution frames'
    required: false
    default: '50'

  timeout:
    description: 'Timeout per frame in milliseconds'
    required: false
    default: '300000'

  auto-approve:
    description: 'Skip plan approval prompt'
    required: false
    default: 'false'

  output-file:
    description: 'Save result to file'
    required: false

  json-output:
    description: 'Output result as JSON'
    required: false
    default: 'false'

  upload-artifacts:
    description: 'Upload result as workflow artifact'
    required: false
    default: 'true'

  artifact-name:
    description: 'Name for uploaded artifact'
    required: false
    default: 'smithers-result'

  tui:
    description: 'Enable TUI mode (requires terminal)'
    required: false
    default: 'false'

  approval-gate:
    description: 'Require manual approval before execution'
    required: false
    default: 'false'

  approval-timeout:
    description: 'Timeout for manual approval in milliseconds'
    required: false
    default: '3600000'

outputs:
  result:
    description: 'Execution result'

  success:
    description: 'Whether execution succeeded'

  frames:
    description: 'Number of frames executed'

  elapsed:
    description: 'Total execution time (ms)'

  artifact-url:
    description: 'URL to uploaded artifact'

runs:
  using: 'node20'
  main: 'dist/index.js'
